[package]
name = "whisper-discord-bot"
version = "0.1.0"
edition = "2021"

[lib]
name = "whisperdiscordbot"
path = "src/lib.rs"

[dependencies]
whisper-rs = { version = "0.11.1", features = ["cuda"] }
hound = "3"

[dev-dependencies]
walkdir = "2"
chrono = "0.4"